Repository wilderPariona/product-app-js-OOP, pull requests merged in 2020-03, with the labels that each got.

#1 :lipstick: update UI, form add products
  assets/css/style.css
  index.html
Labels: good first issue, size/M

#2 update add Products and remove products
  .editorconfig
  assets/js/index.js
  index.html
Labels: size/L

#3 :ok_hand: update add Products and remove products (#2)
  .editorconfig
  assets/js/index.js
  index.html
Labels: size/L

#5 :bug: fix redirect home
  index.html
Labels: size/XS

#6 :bug: fix redirect home (#5)
  index.html
Labels: size/XS
